### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by nnnlog** [nnnlog/SSUrade#1]
# Feature TODO
* [ ] 버스 실시간 도착 정보 조회 (742, 752, 753, 040, 6019 / 상도역 - ... - 숭실대입구역 - 숭실대중문앞 - 숭실대별관앞 - ... - 남성역)
  * [ ] 그 이외 숭실대입구역만 경유하는 버스 지원? (상도 - 숭실대입구 - 서울대입구)
  * [ ] 동작14 지원?
* [ ] 지하철 실시간 도착 정보 조회 (숭실대입구역, 상도역, 남성역)
* [ ] 학생 식당, 기숙사 식당 메뉴 조회
* [ ] 학사/학과별 공지 사항 조회 및 키워드 알림 전송
* [ ] 이수 과목 엑셀로 내보내기 지원
  * [ ] 삼성 공채 시 사용할 수 있도록 할지?

---
# Previous TODO

## 2.0 TODO
* [x] Play store 업로드 (https://play.google.com/store/apps/details?id=com.nnnlog.ssurade)

## 빠른시일 내 TODO
* [ ] 메인 UI 변경 [2.5.x]
* [ ] csv export 지원
* [x] 장학 알림 및 조회 지원
* [x] iOS 지원

## ~ 2.4.x Completed TODO
* [x] 크롤링 실행 로직 변경 (Javascript 코드로 동작, 외부에서 로딩 등)
* [x] 백그라운드 크롤링 도입 (백엔드 필요, 백그라운드에서 서버로부터 데이터 받은 후 알림 전송할 예정)
* [x] 학기별 성적 크롤링 시 "학기별 성적" 참고 (입학/졸업연도 조회 삭제) [2.3.x]
* [x] 성적 상세 정보 조회 [2.3.x]
* [x] 성적 통계 조회 (이수구분별 성적, 전공 평점, 전체 평점, 학기별 평점 조회) [2.4.x]
* [x] 기타 학사 관련 기능 추가 (1학기 개강 전까지 작업 / 채플 출결) [2.4.x]

## 2.0.0 Completed TODO
* [x] 스크린샷 기능
* [x] 데이터 구조 갈아엎기
* [x] 깃허브 링크 보여주기
* [x] 자동 로그인 백그라운드에서 실행
* [x] 크롤링 구조 갈아엎기 (병렬 실행)
* [x] Google Analytics (Firebase)
* [x] Google Analytics (크롤링 timings 측정 / 앱 버전 수집 등)
* [x] 오류 기록용 디버깅 로그/공유 기능 (sentry.io 이용)
* [x] 개인정보 처리방침 동의
* [x] 현재 학기의 성적이 공개되었는지 확인 (백그라운드 / 학기별 성적 조회 탭 이용)
* [x] 성적 크롤링 방식 변경 (이수구분별 성적표 파싱)
* [x] 전공 평점 (getter만)
* [x] sentry 구체적인 로그 (크롤링 위주로)

## 아마도 하지 않게 될 TODO
* [ ] Dark mode 지원 (디자인부터 해야..)
* [ ] 성적 그래프 (전공 성적 포함)
* [ ] 석차 그래프 (백분율 등)

**Comment by nnnlog** [comment]
크롤링 실행 로직 변경 (Javascript 코드로 동작, 외부에서 로딩 등)
-> #13
